version: "3"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=GoodMeta
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data